version: '3.8'

services:
  avito-shop-service:
    build: .
    container_name: avito-shop-service
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=i_want_the_job
      - DATABASE_PORT=5432
      - DATABASE_USER=${DATABASE_USER:-postgres}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-password}
      - DATABASE_NAME=${TEST_MODE:-shop}
      - DATABASE_HOST=${DATABASE_HOST:-db}
      - TEST_MODE=${TEST_MODE:-shop}
      - SERVER_PORT=8080
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s
    networks:
      - internal

  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shop
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d shop"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - internal

  test_db:
    image: postgres:13
    container_name: postgres_test
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5435:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_db"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - internal

  test-runner:
    build: .
    container_name: test-runner
    environment:
      - DATABASE_USER=test_user
      - DATABASE_PASSWORD=test_password
      - DATABASE_NAME=test_db
      - DATABASE_HOST=test_db
      - DATABASE_PORT=5432
      - TEST_MODE=test_db
    depends_on:
      test_db:
        condition: service_healthy
      avito-shop-service:
        condition: service_started
    networks:
      - internal
    command: ["go", "test", "-v", "./internal/integration"]

volumes:
  pgdata:
  pgdata_test:

networks:
  internal:
